### ISSUE TITLE
群里同时收到>=2个红包时，第二个红包开始不会自动抢

### ISSUE THREAD

**Issue by 459418323** [qingyan1990/luckymoney#1]
在群里，当同时收到多个红包时，只会抢第一个，其余的都不会抢了。第二个只会弹出拆开红包的界面。

when  we received more than one red envelope in wechat group,this tool can't get luckymoney except the first one

**Comment by qingyan1990** [comment]
谢谢提出问题（我本以为没人关注的），我也重现了这个问题，在两秒以内收到多个红包会出现这种情况。我已经修复了这个问题（仅测试了同时两个红包）。原因是代码中的robot变量，在同步读取时发生了读写冲突。你可以测试下新的代码看看会不会产生了新bug

**Comment by hsl313** [comment]
你好！我也发了一个！建议！是否可以有个提示抢到多少！
记录一下！谢谢了！
还有可以添加一下你的微信吗？请教一下！我的邮箱！heshenglong313@163.com

**Comment by qingyan1990** [comment]
这个我暂时做不到哈，而且这是一个小众需求，需要在微信源代码中找到要插入的地方，有点困难，还是直接看红包记录吧，不做这个了。我微信ID是aiyanxu1990

**Comment by 459418323** [comment]
等等我编译一下试试，thank you
