### ISSUE TITLE
反编译微信后找不到包

### ISSUE THREAD

**Issue by lumenghz** [qingyan1990/luckymoney#4]
- 在代码中有这么一段路径：`com.tencent.mm.plugin.luckymoney.ui.LuckyMoneyReceiveUI`，我反编译了微信的包，但是在`com.tencent.mm.plugin`中并没有找到`luckymoney`这个包，我用adb 命令查看了当前所在类，确实是在`com.tencent.mm.plugin.luckymoney.ui.LuckyMoneyReceiveUI`中，我想问作者，这个路径是如何找到的。
- Good New: 本来想修改代码适配`6.3.13`的，发现什么都没改，`6.3.13`也是可以用的。

@qingyan1990 求解惑

**Comment by zhongyi-tong** [comment]
同上，找不到这个包

**Comment by niray** [comment]
同上上，找不到这个包

**Comment by zhongyi-tong** [comment]
找到了，这个包在asset目录下，微信有multidex
assets/secondary-program-dex-jars/secondary-2-dex2jar.jar

感谢@yiranshaxiao

**Comment by niray** [comment]
@geeeeeeeeek  请问用什么方式反编译的。 dex2jar.bat 总会报空指针异常。

**Comment by lumenghz** [comment]
@niray 我是用`dex2jar`和`jdgui`没有异常

**Comment by zhongyi-tong** [comment]
[APK decompiler - Java decompilers](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&cad=rja&uact=8&ved=0ahUKEwjQ1J6_lNnKAhXnxIMKHTtxD7sQFggvMAI&url=http%3A%2F%2Fwww.javadecompilers.com%2Fapk&usg=AFQjCNFSmTC-mg-e15QfGCy7IRP1jDj1Kw&sig2=DafdQ3XlUHp6oLjBsVj1TQ)
在线的，用的[jadx](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjQ1J6_lNnKAhXnxIMKHTtxD7sQFggdMAA&url=https%3A%2F%2Fgithub.com%2Fskylot%2Fjadx&usg=AFQjCNHsBkHZdq7Kd_h6kuyoAPsc1hADPQ&sig2=BBZoty-Cewa6wLVXx-yXyw)这个库，apk直接转成java。

**Comment by niray** [comment]
@lubeast  如果单纯反编译Assets下的secondary-2.dex.jar 也是用的dex2jar么？

**Comment by geeeeeeeeek** [comment]
@niray 是。

**Comment by lumenghz** [comment]
@niray 是的。

**Comment by niray** [comment]
`findAndHookMethod("com.tencent.mm.plugin.luckymoney.ui", loadPackageParam.classLoader, "Gb", new XC_MethodHook() {`
为什么自己单使用这个方法Hook,找不到CLass 呢  java.lang.ClassNotFoundException:

**Comment by Sheng0** [comment]
@lubeast 我代码看不懂，我也想看看升级了微信改什么。。。结果发现只改了readme

**Comment by lumenghz** [comment]
@Sheng0 作者提供的这个代码在最近的三个版本`4.3.9`，`4.3.11`和`4.3.13`都是可以使用的，并不需要修改什么东西。我研究了一下作者的代码，我觉得如果要是微信端做了修改我们需要适配的话，基本上改的可能就是如果微信针对结构和其中构造方法做了调整，需要针对其做相应的修改，或者某个字段修改了，但是这种发生的可能性不是很大。

我和你的观点倒不是很一样，代码可以看得懂，我唯一好奇的就是作者是怎么找出那些包，只要提取`b.class`中的`a(..)`构造方法就可以得到notification内容。我好奇的是他是怎么找到的。所以我新提出了一个`issue`等作者解惑。

**Comment by Sheng0** [comment]
@lubeast 我做网站开发的。对安卓不了解，不过你说的这个我也很好奇。

**Comment by ghost** [comment]
把apk打开，里面任何一个文件都有可能。但也有一些规律的。assets这个文件夹就值得关注。

**Comment by duxinpi** [comment]
谁知道如何正编译回去，apktool 没法build原因1. 有的id命名变成了aa，ab，。。。。其中if 和do这两个名字被当成了关键字。 这个应该不难解决，重命名这两个id，和相应的所有使用地点吧。但是发现 所有的res文件跑到了unknown里去了。而且成了乱码。 导致的问题就是 在res里面命名为if和do的我没法重命名。

**Comment by ghost** [comment]
直接修改微信会有问题的。 那是加密程序处理的结果。

在 2016年6月4日 上午2:10，duxinpi notifications@github.com写道：

**Comment by ghost** [comment]
服务器有签名验证的。修改过的包到时会运行失败。

在 2016年6月6日 下午12:19，X Fun xfunforx@gmail.com写道：

**Comment by niray** [comment]
@lubeast  发现微信Android版6.3.15包结构变了,之前放在Assets/secondary-program-dex-jars/中的jar包都不见了,只在此目录下发现一个metadata.txt  , 不知道之前的secondary-*-dex2jar.jar以何种方式存放了..

**Comment by ghost** [comment]
@niray 解压那个apk就可以看到啊。 直接把那几个dex复制出来用baksmali反编译就能找到你要的类。
刚刚用最新的6.3.18试过。/com/tencent/mm/plugin/luckymoney 这个目录下面就是红包插件的文件了。

**Comment by ghost** [comment]
@lubeast 要了解如何找到那个起始类的话，需要了解微信的行为。收到任何消息（不静音）时，微信都会弹出一条通知出来。通过这个点可以找到最开始接收到消息后的处理逻辑。刚好这里服务器发下的加密数据已经解密好，就直接用了。时间点上如果想更提一点的话也是可以的。但这个时间差真的不大。

**Comment by lumenghz** [comment]
@xfunforx 这个是你的工程你怎么不拿去维护啊，这么好的东西，感觉比其他的好用多了. @qingyan1990 这个人明显不会管的 😄

**Comment by ghost** [comment]
哈哈。。。你这样说，@qingyan1990 会生气了。到时打你PP就不好了。

已经没有东西搞了啊。。。对于我的目标已经完成了。该放手的时候就应该放手了。

2016-06-12 20:45 GMT+08:00 LuMeng notifications@github.com:
