### ISSUE TITLE
请教作者的问题

### ISSUE THREAD

**Issue by lumenghz** [qingyan1990/luckymoney#5]
我和师傅看了之后觉得有些地方是很神奇的，就是有些微信使用的类和方法你是怎么找到的。
e.g：
- 作者是如何找到在`com.tencent.mm.booter.notification.b`这个类中有`a(method, loadpackageparam, string, string, int, int, boolean, )`并且知道微信的消息就是通过这个方法来进行一些操作的，通俗来说，就是你是如何定位到这个方法的。

昨天师傅给我说了这个`project`之后对这个很感兴趣，请指教。

**Comment by qingyan1990** [comment]
抱歉啊，才看到，我这个项目一开始是从xfunforx那里fork的，原作者后面删掉了repository，但github上还能找到一些早期fork的版本。我看过最初版的代码，只能看出xfunforx曾通过查看log来确定hook的位置。不过还有一些trick点我现在也没弄清是怎么找到的。原作者也是从百万行代码中找到了hook点，的确付出了很大心血。http://coolapk.com/apk/com.xfunforx.elf 这是作者最新的抢红包apk，只是不再开源源代码了

**Comment by qingyan1990** [comment]
https://github.com/qingyan1990/tempory 这个是我当初备份得一份原始的代码，里面commit里有一些原作者开发的思路。抱歉啊，我自己能力有限，也无法回答一些问题

**Comment by lumenghz** [comment]
没关系，同样感谢你的回复和分享 :D

**Comment by ghost** [comment]
其实也就是反复的阅读mm的源代码啊。不断的尝试啊。
